name: comics
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  cupertino_icons: ^1.0.8
  intl_phone_number_input: ^0.7.4
  http: ^1.2.2
  shared_preferences: ^2.3.3
#  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/comics/
    - assets/icons/
    - assets/images/
